name: randnum workflow
on:
  release:
    types: [published]
  
jobs:
  push_to_docker:
    runs-on: ubuntu-latest
    steps:

      # https://github.com/marketplace/actions/checkout
      # This action checks-out repository under $GITHUB_WORKSPACE, so that workflow can access it.
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      # https://github.com/marketplace/actions/docker-login
      # To login to docker account 
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: print tag name
        run: echo ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:${{ github.ref_name }}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      # Build and push with image tag as <account name>/<image name>:<tag> format.
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/randum_number:${{ github.ref_name }}

      # https://github.com/marketplace/actions/slack-send
      # To post message on slack channel
      - name: Send custom JSON data to Slack
        id: Slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "SA54 Submission",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Name: ${{ secrets.USER_NAME }}\nMatriculation: ${{ secrets.MAT_NUMBER }}\nEmail: ${{ secrets.EMAIL }}\nRepo: ${{ github.repositoryUrl }}\nImage name: ${{ github.repository }}:${{ github.ref_name }}\nImage url: ${{ secrets.IMAGE_URL }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
